name: Recovery Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'Manifest URL'
        required: true
        default: 'https://github.com'
      MANIFEST_BRANCH:
        description: 'Manifest Branch'
        required: true
        default: 'twrp-11'
      DEVICE_TREE_URL:
        description: 'Device Tree URL'
        required: true
        default: ''
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch'
        required: true
        default: 'main'
      DEVICE_PATH:
        description: 'Device Path'
        required: true
        default: 'device/oukitel/WP16'
      DEVICE_NAME:
        description: 'Device Name'
        required: true
        default: 'WP16'
      MAKEFILE_NAME:
        description: 'Makefile Name'
        required: true
        default: 'twrp_WP16'
      BUILD_TARGET:
        description: 'Build Target'
        required: true
        default: 'recoveryimage'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cleanup Disk Space
      uses: rokibhasansagar/slimhub_actions@main

    - name: Install Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3 python-is-python3

    - name: Install Google Repo Tool Securely
      run: |
        mkdir -p ~/bin
        curl -s https://googleapis.com > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize Repo and Sync
      run: |
        mkdir workspace
        cd workspace
        git config --global user.name "Github Action"
        git config --global user.email "action@github.com"
        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Clone Device Tree
      run: |
        cd workspace
        git clone --depth=1 ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ${{ github.event.inputs.DEVICE_PATH }}

    - name: Build TWRP Recovery
      run: |
        cd workspace
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng
        make clean
        make ${{ github.event.inputs.BUILD_TARGET }} -j$(nproc --all)

    - name: Upload Finished Image
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-${{ github.event.inputs.DEVICE_NAME }}-Image
        path: workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.img
